# Generated by Django 3.1a1 on 2020-05-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('definition', models.CharField(max_length=400)),
                ('video', models.FileField(upload_to='')),
                ('genre', models.CharField(choices=[('Cartoons', 'Cartoons'), ('Comedy', 'Comedy'), ('romantic', 'romantic')], max_length=10)),
                ('prep_time', models.PositiveIntegerField()),
                ('country', models.TextField()),
            ],
        ),
    ]
